/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const getHealth200Schema = z.string()

export const getHealthQueryResponseSchema = getHealth200Schema