/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const getRooms200Schema = z.array(
  z.object({
    id: z.uuid(),
    name: z.string(),
  }),
)

export const getRoomsQueryResponseSchema = getRooms200Schema