/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const getRooms200Schema = z.any()

export const getRoomsQueryResponseSchema = z.lazy(() => getRooms200Schema)