export type { GetHealthQueryKey } from './hooks/useGetHealth.ts'
export type { GetHealthSuspenseQueryKey } from './hooks/useGetHealthSuspense.ts'
export type { GetRoomsQueryKey } from './hooks/useGetRooms.ts'
export type { GetRoomsSuspenseQueryKey } from './hooks/useGetRoomsSuspense.ts'
export type { GetHealth200, GetHealthQueryResponse, GetHealthQuery } from './types/GetHealth.ts'
export type { GetRooms200, GetRoomsQueryResponse, GetRoomsQuery } from './types/GetRooms.ts'
export { getHealthQueryKey, getHealth, getHealthQueryOptions, useGetHealth } from './hooks/useGetHealth.ts'
export { getHealthSuspenseQueryKey, getHealthSuspense, getHealthSuspenseQueryOptions, useGetHealthSuspense } from './hooks/useGetHealthSuspense.ts'
export { getRoomsQueryKey, getRooms, getRoomsQueryOptions, useGetRooms } from './hooks/useGetRooms.ts'
export { getRoomsSuspenseQueryKey, getRoomsSuspense, getRoomsSuspenseQueryOptions, useGetRoomsSuspense } from './hooks/useGetRoomsSuspense.ts'
export { getHealth200Schema, getHealthQueryResponseSchema } from './zod/getHealthSchema.ts'
export { getRooms200Schema, getRoomsQueryResponseSchema } from './zod/getRoomsSchema.ts'