/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetRoomsQueryResponse } from '../types/GetRooms.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { getRoomsQueryResponseSchema } from '../zod/getRoomsSchema.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getRoomsQueryKey = () => [{ url: '/rooms/' }] as const

export type GetRoomsQueryKey = ReturnType<typeof getRoomsQueryKey>

/**
 * {@link /rooms/}
 */
export async function getRooms(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetRoomsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/rooms/`,
    baseURL: 'http://localhost:3000',
    ...requestConfig,
  })
  return getRoomsQueryResponseSchema.parse(res.data)
}

export function getRoomsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRoomsQueryKey()
  return queryOptions<GetRoomsQueryResponse, ResponseErrorConfig<Error>, GetRoomsQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getRooms(config)
    },
  })
}

/**
 * {@link /rooms/}
 */
export function useGetRooms<TData = GetRoomsQueryResponse, TQueryData = GetRoomsQueryResponse, TQueryKey extends QueryKey = GetRoomsQueryKey>(
  options: {
    query?: Partial<QueryObserverOptions<GetRoomsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getRoomsQueryKey()

  const query = useQuery(
    {
      ...getRoomsQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}