/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetRoomQuestionsQueryResponse, GetRoomQuestionsPathParams } from '../types/GetRoomQuestions.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getRoomQuestionsQueryKey = (roomId: GetRoomQuestionsPathParams['roomId']) =>
  [{ url: '/rooms/:roomId/questions', params: { roomId: roomId } }] as const

export type GetRoomQuestionsQueryKey = ReturnType<typeof getRoomQuestionsQueryKey>

/**
 * {@link /rooms/:roomId/questions}
 */
export async function getRoomQuestions(roomId: GetRoomQuestionsPathParams['roomId'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetRoomQuestionsQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/rooms/${roomId}/questions`,
    baseURL: 'http://localhost:3000',
    ...requestConfig,
  })
  return res.data
}

export function getRoomQuestionsQueryOptions(roomId: GetRoomQuestionsPathParams['roomId'], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRoomQuestionsQueryKey(roomId)
  return queryOptions<GetRoomQuestionsQueryResponse, ResponseErrorConfig<Error>, GetRoomQuestionsQueryResponse, typeof queryKey>({
    enabled: !!roomId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getRoomQuestions(roomId, config)
    },
  })
}

/**
 * {@link /rooms/:roomId/questions}
 */
export function useGetRoomQuestions<
  TData = GetRoomQuestionsQueryResponse,
  TQueryData = GetRoomQuestionsQueryResponse,
  TQueryKey extends QueryKey = GetRoomQuestionsQueryKey,
>(
  roomId: GetRoomQuestionsPathParams['roomId'],
  options: {
    query?: Partial<QueryObserverOptions<GetRoomQuestionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getRoomQuestionsQueryKey(roomId)

  const query = useQuery(
    {
      ...getRoomQuestionsQueryOptions(roomId, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}