/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetRoomsQueryResponse } from '../types/GetRooms.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { getRoomsQueryResponseSchema } from '../zod/getRoomsSchema.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getRoomsSuspenseQueryKey = () => [{ url: '/rooms/' }] as const

export type GetRoomsSuspenseQueryKey = ReturnType<typeof getRoomsSuspenseQueryKey>

/**
 * {@link /rooms/}
 */
export async function getRoomsSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetRoomsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/rooms/`, ...requestConfig })
  return getRoomsQueryResponseSchema.parse(res.data)
}

export function getRoomsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRoomsSuspenseQueryKey()
  return queryOptions<GetRoomsQueryResponse, ResponseErrorConfig<Error>, GetRoomsQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getRoomsSuspense(config)
    },
  })
}

/**
 * {@link /rooms/}
 */
export function useGetRoomsSuspense<TData = GetRoomsQueryResponse, TQueryKey extends QueryKey = GetRoomsSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<GetRoomsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getRoomsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getRoomsSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}