/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { GetHealthQueryResponse } from '../types/GetHealth.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { getHealthQueryResponseSchema } from '../zod/getHealthSchema.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getHealthSuspenseQueryKey = () => [{ url: '/health' }] as const

export type GetHealthSuspenseQueryKey = ReturnType<typeof getHealthSuspenseQueryKey>

/**
 * {@link /health}
 */
export async function getHealthSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<GetHealthQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/health`, ...requestConfig })
  return getHealthQueryResponseSchema.parse(res.data)
}

export function getHealthSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getHealthSuspenseQueryKey()
  return queryOptions<GetHealthQueryResponse, ResponseErrorConfig<Error>, GetHealthQueryResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getHealthSuspense(config)
    },
  })
}

/**
 * {@link /health}
 */
export function useGetHealthSuspense<TData = GetHealthQueryResponse, TQueryKey extends QueryKey = GetHealthSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<GetHealthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getHealthSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getHealthSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}