/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type { PostRoomQuestionMutationRequest, PostRoomQuestionMutationResponse, PostRoomQuestionPathParams } from '../types/PostRoomQuestion.ts'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postRoomQuestionMutationKey = () => [{ url: '/rooms/{roomId}/questions' }] as const

export type PostRoomQuestionMutationKey = ReturnType<typeof postRoomQuestionMutationKey>

/**
 * {@link /rooms/:roomId/questions}
 */
export async function postRoomQuestion(
  roomId: PostRoomQuestionPathParams['roomId'],
  data: PostRoomQuestionMutationRequest,
  config: Partial<RequestConfig<PostRoomQuestionMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<PostRoomQuestionMutationResponse, ResponseErrorConfig<Error>, PostRoomQuestionMutationRequest>({
    method: 'POST',
    url: `/rooms/${roomId}/questions`,
    baseURL: 'http://localhost:3000',
    data: requestData,
    ...requestConfig,
  })
  return res.data
}

/**
 * {@link /rooms/:roomId/questions}
 */
export function usePostRoomQuestion<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostRoomQuestionMutationResponse,
      ResponseErrorConfig<Error>,
      { roomId: PostRoomQuestionPathParams['roomId']; data: PostRoomQuestionMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostRoomQuestionMutationRequest>> & { client?: typeof fetch }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postRoomQuestionMutationKey()

  return useMutation<
    PostRoomQuestionMutationResponse,
    ResponseErrorConfig<Error>,
    { roomId: PostRoomQuestionPathParams['roomId']; data: PostRoomQuestionMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ roomId, data }) => {
        return postRoomQuestion(roomId, data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}