/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetRoomsByRoomIdQuestionsPathParams = {
  /**
   * @type string, uuid
   */
  roomId: string
}

export type GetRoomsByRoomIdQuestions200 = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  question: string
  answer: string | null
  createdAt: string | string | number
}[]

export type GetRoomsByRoomIdQuestionsQueryResponse = GetRoomsByRoomIdQuestions200

export type GetRoomsByRoomIdQuestionsQuery = {
  Response: GetRoomsByRoomIdQuestions200
  PathParams: GetRoomsByRoomIdQuestionsPathParams
  Errors: any
}