/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetRooms200 = any

export type GetRoomsQueryResponse = GetRooms200

export type GetRoomsQuery = {
  Response: GetRooms200
  Errors: any
}