/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetRoomQuestionsPathParams = {
  /**
   * @type string, uuid
   */
  roomId: string
}

export type GetRoomQuestions200 = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  question: string
  answer: string | null
  createdAt: string | string | number
}[]

export type GetRoomQuestionsQueryResponse = GetRoomQuestions200

export type GetRoomQuestionsQuery = {
  Response: GetRoomQuestions200
  PathParams: GetRoomQuestionsPathParams
  Errors: any
}