/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetRooms200 = {
  /**
   * @type string, uuid
   */
  id: string
  /**
   * @type string
   */
  name: string
  createdAt: string | string | number
  /**
   * @type number
   */
  questionsCount: number
}[]

export type GetRoomsQueryResponse = GetRooms200

export type GetRoomsQuery = {
  Response: GetRooms200
  Errors: any
}