/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostRoomsByRoomIdQuestionsPathParams = {
  /**
   * @type string, uuid
   */
  roomId: string
}

export type PostRoomsByRoomIdQuestions201 = {
  /**
   * @type string, uuid
   */
  questionId: string
}

export type PostRoomsByRoomIdQuestionsMutationRequest = {
  /**
   * @type string
   */
  question: string
}

export type PostRoomsByRoomIdQuestionsMutationResponse = PostRoomsByRoomIdQuestions201

export type PostRoomsByRoomIdQuestionsMutation = {
  Response: PostRoomsByRoomIdQuestions201
  Request: PostRoomsByRoomIdQuestionsMutationRequest
  PathParams: PostRoomsByRoomIdQuestionsPathParams
  Errors: any
}