/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostRooms201 = {
  /**
   * @type string, uuid
   */
  roomId: string
}

export type PostRoomsMutationRequest = {
  /**
   * @minLength 3
   * @type string
   */
  name: string
  /**
   * @type string
   */
  description: string
}

export type PostRoomsMutationResponse = PostRooms201

export type PostRoomsMutation = {
  Response: PostRooms201
  Request: PostRoomsMutationRequest
  Errors: any
}