/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostUploadAudioPathParams = {
  /**
   * @type string, uuid
   */
  roomId: string
}

export type PostUploadAudio201 = {
  /**
   * @type string, uuid
   */
  chunkId: string
}

export type PostUploadAudioMutationRequest = {
  /**
   * @default "File"
   * @type string, binary
   */
  file: Blob
}

export type PostUploadAudioMutationResponse = PostUploadAudio201

export type PostUploadAudioMutation = {
  Response: PostUploadAudio201
  Request: PostUploadAudioMutationRequest
  PathParams: PostUploadAudioPathParams
  Errors: any
}