/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostRoomQuestionPathParams = {
  /**
   * @type string, uuid
   */
  roomId: string
}

export type PostRoomQuestion201 = {
  /**
   * @type string, uuid
   */
  questionId: string
  answer: string | null
}

export type PostRoomQuestionMutationRequest = {
  /**
   * @type string
   */
  question: string
}

export type PostRoomQuestionMutationResponse = PostRoomQuestion201

export type PostRoomQuestionMutation = {
  Response: PostRoomQuestion201
  Request: PostRoomQuestionMutationRequest
  PathParams: PostRoomQuestionPathParams
  Errors: any
}